name: "Deploy site"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

env:
  DEPLOY: >-
    ${{
    github.event_name != 'pull_request'
    &&
    github.ref == 'refs/heads/master'
    }}
  OUTPUT: _html

jobs:
  build:
    name: Build lektor website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Lektor
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install lektor
      - name: Build lektor website
        run: lektor build -O '${{ env.OUTPUT }}'

      - name: Deploy lektor website
        if: env.DEPLOY == 'true'
        run: lektor deploy -O '${{ env.OUTPUT }}' ghpages-https
        env:
          LEKTOR_DEPLOY_USERNAME: imflop
          LEKTOR_DEPLOY_PASSWORD: ${{ secrets.LEKTOR_GITHUB_TOKEN }}